[package]
name = "idlc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0.1"
serde = { version = "1.0", features = ["derive"] }
liquid = "0.24.0"
liquid-core = "0.24.0"
uuid = "0.8"
