[workspace]
members = [
    "crosscom/runtime/rust",
    "radiance/radiance",
    "radiance/radiance_editor",
    "yaobow/common",
    "yaobow/opengb",
    "yaobow/fileformats",
    "yaobow/shared",
    "yaobow/yaobow",
    "yaobow/yaobow_editor",
    "tools/pol_exporter",
]
resolver = "2"

[patch.crates-io]
ffmpeg-sys = { git = "https://github.com/dontpanic92/rust-ffmpeg-sys.git" }
vk-mem = { git = "https://github.com/gwihlidal/vk-mem-rs" }

[profile.release-with-symbol]
inherits = "release"
debug = true
