[package]
name = "radiance"
version = "0.1.0"
authors = ["dontpanic <lishengqiu.hit@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
ash = "0.30.0"
vk-mem = { git = "https://github.com/gwihlidal/vk-mem-rs" }
memoffset = "0.5.3"
lazy_static = "1.2.0"
image = "0.23.0"
backtrace = "0.3.44"
bitflags = "1.2.1"
imgui = "0.3.0"
imgui-rs-vulkan-renderer = { path = "../../imgui-rs-vulkan-renderer" }
radiance_assets = { path = "../../radiance_assets" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["winuser", "libloaderapi", "errhandlingapi"] }
