[package]
name = "asdebug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow="1.0"
eframe = "0.22"
env_logger = "0.10"
interprocess = "1.2"
